export const currencies = {
  VND: {
    symbol: '₫',
    name: 'Vietnamese Dong',
    code: 'VND',
    locale: 'vn',
  },
  THB: {
    symbol: '฿',
    name: 'Thai Baht',
    code: 'THB',
    locale: 'th',
  },
  LAK: {
    symbol: '₭',
    name: 'Lao Kip',
    code: 'LAK',
    locale: 'lo',
  },
  KHR: {
    symbol: '៛',
    name: 'Cambodian Riel',
    code: 'KHR',
    locale: 'kh',
  },
  MMK: {
    symbol: 'K',
    name: 'Myanmar Kyat',
    code: 'MMK',
    locale: 'my',
  },
  SGD: {
    symbol: '$',
    name: 'Singapore Dollar',
    code: 'SGD',
    locale: 'sg',
  },
  MYR: {
    symbol: 'RM',
    name: 'Malaysian Ringgit',
    code: 'MYR',
    locale: 'my',
  },
  IDR: {
    symbol: 'Rp',
    name: 'Indonesian Rupiah',
    code: 'IDR',
    locale: 'id',
  },
  PHP: {
    symbol: '₱',
    name: 'Philippine Peso',
    code: 'PHP',
    locale: 'ph',
  },
  KRW: {
    symbol: '₩',
    name: 'Korean Won',
    code: 'KRW',
    locale: 'kr',
  },
  JPY: {
    symbol: '¥',
    name: 'Japanese Yen',
    code: 'JPY',
    locale: 'jp',
  },
  CNY: {
    symbol: '¥',
    name: 'Chinese Yuan',
    code: 'CNY',
    locale: 'cn',
  },
  USD: {
    symbol: '$',
    name: 'US Dollar',
    code: 'USD',
    locale: 'us',
  },
  EUR: {
    symbol: '€',
    name: 'Euro',
    code: 'EUR',
    locale: 'eu',
  },
  GBP: {
    symbol: '£',
    name: 'British Pound',
    code: 'GBP',
    locale: 'gb',
  },
  AUD: {
    symbol: '$',
    name: 'Australian Dollar',
    code: 'AUD',
    locale: 'au',
  },
  NZD: {
    symbol: '$',
    name: 'New Zealand Dollar',
    code: 'NZD',
    locale: 'nz',
  },
  CAD: {
    symbol: '$',
    name: 'Canadian Dollar',
    code: 'CAD',
    locale: 'ca',
  },
  CHF: {
    symbol: 'CHF',
    name: 'Swiss Franc',
    code: 'CHF',
    locale: 'ch',
  },
  SEK: {
    symbol: 'kr',
    name: 'Swedish Krona',
    code: 'SEK',
    locale: 'se',
  },
  DKK: {
    symbol: 'kr',
    name: 'Danish Krone',
    code: 'DKK',
    locale: 'dk',
  },
  NOK: {
    symbol: 'kr',
    name: 'Norwegian Krone',
    code: 'NOK',
    locale: 'no',
  },
  RUB: {
    symbol: '₽',
    name: 'Russian Ruble',
    code: 'RUB',
    locale: 'ru',
  },
  INR: {
    symbol: '₹',
    name: 'Indian Rupee',
    code: 'INR',
    locale: 'in',
  },
  PKR: {
    symbol: '₨',
    name: 'Pakistani Rupee',
    code: 'PKR',
    locale: 'pk',
  },
  BDT: {
    symbol: '৳',
    name: 'Bangladeshi Taka',
    code: 'BDT',
    locale: 'bd',
  },
  NPR: {
    symbol: '₨',
    name: 'Nepalese Rupee',
    code: 'NPR',
    locale: 'np',
  },
  LKR: {
    symbol: '₨',
    name: 'Sri Lankan Rupee',
    code: 'LKR',
    locale: 'lk',
  },
  MVR: {
    symbol: 'Rf',
    name: 'Maldivian Rufiyaa',
    code: 'MVR',
    locale: 'mv',
  },
  AED: {
    symbol: 'د.إ',
    name: 'United Arab Emirates Dirham',
    code: 'AED',
    locale: 'ae',
  },
  SAR: {
    symbol: 'ر.س',
    name: 'Saudi Riyal',
    code: 'SAR',
    locale: 'sa',
  },
  QAR: {
    symbol: 'ر.ق',
    name: 'Qatari Riyal',
    code: 'QAR',
    locale: 'qa',
  },
  OMR: {
    symbol: 'ر.ع.',
    name: 'Omani Rial',
    code: 'OMR',
    locale: 'om',
  },
  KWD: {
    symbol: 'د.ك',
    name: 'Kuwaiti Dinar',
    code: 'KWD',
    locale: 'kw',
  },
  BHD: {
    symbol: 'د.ب',
    name: 'Bahraini Dinar',
    code: 'BHD',
    locale: 'bh',
  },
  JOD: {
    symbol: 'د.ا',
    name: 'Jordanian Dinar',
    code: 'JOD',
    locale: 'jo',
  },
  ILS: {
    symbol: '₪',
    name: 'Israeli Shekel',
    code: 'ILS',
    locale: 'il',
  },
  TRY: {
    symbol: '₺',
    name: 'Turkish Lira',
    code: 'TRY',
    locale: 'tr',
  },
  ZAR: {
    symbol: 'R',
    name: 'South African Rand',
    code: 'ZAR',
    locale: 'za',
  },
  BRL: {
    symbol: 'R$',
    name: 'Brazilian Real',
    code: 'BRL',
    locale: 'br',
  },
  ARS: {
    symbol: '$',
    name: 'Argentine Peso',
    code: 'ARS',
    locale: 'ar',
  },
  CLP: {
    symbol: '$',
    name: 'Chilean Peso',
    code: 'CLP',
    locale: 'cl',
  },
  MXN: {
    symbol: '$',
    name: 'Mexican Peso',
    code: 'MXN',
    locale: 'mx',
  },
  COP: {
    symbol: '$',
    name: 'Colombian Peso',
    code: 'COP',
    locale: 'co',
  },
  PEN: {
    symbol: 'S/',
    name: 'Peruvian Sol',
    code: 'PEN',
    locale: 'pe',
  },
  VES: {
    symbol: 'Bs',
    name: 'Venezuelan Bolívar',
    code: 'VES',
    locale: 've',
  },
  BOB: {
    symbol: 'Bs',
    name: 'Bolivian Boliviano',
    code: 'BOB',
    locale: 'bo',
  },
  PYG: {
    symbol: '₲',
    name: 'Paraguayan Guarani',
    code: 'PYG',
    locale: 'py',
  },
  UYU: {
    symbol: '$',
    name: 'Uruguayan Peso',
    code: 'UYU',
    locale: 'uy',
  },
  CRC: {
    symbol: '₡',
    name: 'Costa Rican Colon',
    code: 'CRC',
    locale: 'cr',
  },
  DOP: {
    symbol: 'RD$',
    name: 'Dominican Peso',
    code: 'DOP',
    locale: 'do',
  },
  GTQ: {
    symbol: 'Q',
    name: 'Guatemalan Quetzal',
    code: 'GTQ',
    locale: 'gt',
  },
  HNL: {
    symbol: 'L',
    name: 'Honduran Lempira',
    code: 'HNL',
    locale: 'hn',
  },
  NIO: {
    symbol: 'C$',
    name: 'Nicaraguan Cordoba',
    code: 'NIO',
    locale: 'ni',
  },
  SVC: {
    symbol: '$',
    name: 'Salvadoran Colon',
    code: 'SVC',
    locale: 'sv',
  },
  BZD: {
    symbol: 'BZ$',
    name: 'Belize Dollar',
    code: 'BZD',
    locale: 'bz',
  },
  BSD: {
    symbol: '$',
    name: 'Bahamian Dollar',
    code: 'BSD',
    locale: 'bs',
  },
  KYD: {
    symbol: '$',
    name: 'Cayman Islands Dollar',
    code: 'KYD',
    locale: 'ky',
  },
  JMD: {
    symbol: 'J$',
    name: 'Jamaican Dollar',
    code: 'JMD',
    locale: 'jm',
  },
  TTD: {
    symbol: 'TT$',
    name: 'Trinidad and Tobago Dollar',
    code: 'TTD',
    locale: 'tt',
  },
  XCD: {
    symbol: 'EC$',
    name: 'Eastern Caribbean Dollar',
    code: 'XCD',
    locale: 'gd',
  },
  ANG: {
    symbol: 'ƒ',
    name: 'Netherlands Antillean Guilder',
    code: 'ANG',
    locale: 'cw',
  },
  BBD: {
    symbol: 'Bds$',
    name: 'Barbadian Dollar',
    code: 'BBD',
    locale: 'bb',
  },
  BMD: {
    symbol: '$',
    name: 'Bermudian Dollar',
    code: 'BMD',
    locale: 'bm',
  },
  BND: {
    symbol: 'B$',
    name: 'Brunei Dollar',
    code: 'BND',
    locale: 'bn',
  },
  FJD: {
    symbol: 'FJ$',
    name: 'Fijian Dollar',
    code: 'FJD',
    locale: 'fj',
  },
  GYD: {
    symbol: 'G$',
    name: 'Guyanese Dollar',
    code: 'GYD',
    locale: 'gy',
  },
  LRD: {
    symbol: 'L$',
    name: 'Liberian Dollar',
    code: 'LRD',
    locale: 'lr',
  },
  SRD: {
    symbol: '$',
    name: 'Surinamese Dollar',
    code: 'SRD',
    locale: 'sr',
  },
  TWD: {
    symbol: 'NT$',
    name: 'New Taiwan Dollar',
    code: 'TWD',
    locale: 'tw',
  },
  TND: {
    symbol: 'د.ت',
    name: 'Tunisian Dinar',
    code: 'TND',
    locale: 'tn',
  },
  MAD: {
    symbol: 'د.م.',
    name: 'Moroccan Dirham',
    code: 'MAD',
    locale: 'ma',
  },
  DZD: {
    symbol: 'د.ج',
    name: 'Algerian Dinar',
    code: 'DZD',
    locale: 'dz',
  },
  EGP: {
    symbol: 'ج.م',
    name: 'Egyptian Pound',
    code: 'EGP',
    locale: 'eg',
  },
  SDG: {
    symbol: 'ج.س',
    name: 'Sudanese Pound',
    code: 'SDG',
    locale: 'sd',
  },
  LYD: {
    symbol: 'ل.د',
    name: 'Libyan Dinar',
    code: 'LYD',
    locale: 'ly',
  },
  SOS: {
    symbol: 'S',
    name: 'Somali Shilling',
    code: 'SOS',
    locale: 'so',
  },
  GHS: {
    symbol: '₵',
    name: 'Ghanaian Cedi',
    code: 'GHS',
    locale: 'gh',
  },
  ZMW: {
    symbol: 'ZK',
    name: 'Zambian Kwacha',
    code: 'ZMW',
    locale: 'zm',
  },
  MWK: {
    symbol: 'MK',
    name: 'Malawian Kwacha',
    code: 'MWK',
    locale: 'mw',
  },
  UGX: {
    symbol: 'USh',
    name: 'Ugandan Shilling',
    code: 'UGX',
    locale: 'ug',
  },
  RWF: {
    symbol: 'FRw',
    name: 'Rwandan Franc',
    code: 'RWF',
    locale: 'rw',
  },
  KES: {
    symbol: 'KSh',
    name: 'Kenyan Shilling',
    code: 'KES',
    locale: 'ke',
  },
  TZS: {
    symbol: 'TSh',
    name: 'Tanzanian Shilling',
    code: 'TZS',
    locale: 'tz',
  },
  ETB: {
    symbol: 'Br',
    name: 'Ethiopian Birr',
    code: 'ETB',
    locale: 'et',
  },
  DJF: {
    symbol: 'Fdj',
    name: 'Djiboutian Franc',
    code: 'DJF',
    locale: 'dj',
  },
  KMF: {
    symbol: 'CF',
    name: 'Comorian Franc',
    code: 'KMF',
    locale: 'km',
  },
  SCR: {
    symbol: '₨',
    name: 'Seychellois Rupee',
    code: 'SCR',
    locale: 'sc',
  },
  MUR: {
    symbol: '₨',
    name: 'Mauritian Rupee',
    code: 'MUR',
    locale: 'mu',
  },
  MGA: {
    symbol: 'Ar',
    name: 'Malagasy Ariary',
    code: 'MGA',
    locale: 'mg',
  },
  NAD: {
    symbol: '$',
    name: 'Namibian Dollar',
    code: 'NAD',
    locale: 'na',
  },
  BWP: {
    symbol: 'P',
    name: 'Botswana Pula',
    code: 'BWP',
    locale: 'bw',
  },
  SZL: {
    symbol: 'E',
    name: 'Eswatini Lilangeni',
    code: 'SZL',
    locale: 'sz',
  },
  LSL: {
    symbol: 'L',
    name: 'Lesotho Loti',
    code: 'LSL',
    locale: 'ls',
  },
  MZN: {
    symbol: 'MT',
    name: 'Mozambican Metical',
    code: 'MZN',
    locale: 'mz',
  },
  AOA: {
    symbol: 'Kz',
    name: 'Angolan Kwanza',
    code: 'AOA',
    locale: 'ao',
  },
  ZWL: {
    symbol: 'Z$',
    name: 'Zimbabwean Dollar',
    code: 'ZWL',
    locale: 'zw',
  },
  VUV: {
    symbol: 'VT',
    name: 'Vanuatu Vatu',
    code: 'VUV',
    locale: 'vu',
  },
  PGK: {
    symbol: 'K',
    name: 'Papua New Guinean Kina',
    code: 'PGK',
    locale: 'pg',
  },
  WST: {
    symbol: 'WS$',
    name: 'Samoan Tala',
    code: 'WST',
    locale: 'ws',
  },
  TOP: {
    symbol: 'T$',
    name: 'Tongan Paʻanga',
    code: 'TOP',
    locale: 'to',
  },
  KPW: {
    symbol: '₩',
    name: 'North Korean Won',
    code: 'KPW',
    locale: 'kp',
  },
  BTN: {
    symbol: 'Nu.',
    name: 'Bhutanese Ngultrum',
    code: 'BTN',
    locale: 'bt',
  },
  MNT: {
    symbol: '₮',
    name: 'Mongolian Tögrög',
    code: 'MNT',
    locale: 'mn',
  },
  AFN: {
    symbol: '؋',
    name: 'Afghan Afghani',
    code: 'AFN',
    locale: 'af',
  },
  KGS: {
    symbol: 'лв',
    name: 'Kyrgyzstani Som',
    code: 'KGS',
    locale: 'kg',
  },
  TJS: {
    symbol: 'SM',
    name: 'Tajikistani Somoni',
    code: 'TJS',
    locale: 'tj',
  },
  UZS: {
    symbol: 'лв',
    name: 'Uzbekistani Som',
    code: 'UZS',
    locale: 'uz',
  },
  TMT: {
    symbol: 'm',
    name: 'Turkmenistani Manat',
    code: 'TMT',
    locale: 'tm',
  },
  IRR: {
    symbol: '﷼',
    name: 'Iranian Rial',
    code: 'IRR',
    locale: 'ir',
  },
  IQD: {
    symbol: 'ع.د',
    name: 'Iraqi Dinar',
    code: 'IQD',
    locale: 'iq',
  },
  YER: {
    symbol: '﷼',
    name: 'Yemeni Rial',
    code: 'YER',
    locale: 'ye',
  },
  KZT: {
    symbol: '₸',
    name: 'Kazakhstani Tenge',
    code: 'KZT',
    locale: 'kz',
  },
  BAM: {
    symbol: 'KM',
    name: 'Bosnia and Herzegovina Convertible Mark',
    code: 'BAM',
    locale: 'ba',
  },
  MKD: {
    symbol: 'ден',
    name: 'Macedonian Denar',
    code: 'MKD',
    locale: 'mk',
  },
  ALL: {
    symbol: 'L',
    name: 'Albanian Lek',
    code: 'ALL',
    locale: 'al',
  },
  GEL: {
    symbol: '₾',
    name: 'Georgian Lari',
    code: 'GEL',
    locale: 'ge',
  },
  AMD: {
    symbol: '֏',
    name: 'Armenian Dram',
    code: 'AMD',
    locale: 'am',
  },
  AZN: {
    symbol: '₼',
    name: 'Azerbaijani Manat',
    code: 'AZN',
    locale: 'az',
  },
  BYN: {
    symbol: 'Br',
    name: 'Belarusian Ruble',
    code: 'BYN',
    locale: 'by',
  },
}
